version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
    - "80:80"
    volumes:
      - data:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    args:
      - DATABASE_USER
      - DATABASE_USER_PASSWORD
      - DATABASE_NAME
      - DATABASE_ROOT_PASSWORD
    volumes:
      - data:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  data: