# version: '3'
services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
    - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    restart: always
    depends_on:
      - wordpress
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_NAME
        - DATABASE_ROOT_PASSWORD
        - DATABASE_ROOT
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      args:
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_NAME
        - DATABASE_ROOT_PASSWORD
        - WP_ADMIN_USER
        - WP_ADMIN_PASSWD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASSWD
        - WP_USER_EMAIL
        - WP_URL
        - WP_DB_HOST
        - WP_TITLE
    volumes:
      - wp_data:/var/www/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/guribeir/data/db_data/
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/guribeir/data/wp_data/

networks:
  mynetwork:
    driver: bridge
    name: mynetwork
