version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
    - "80:80"
    volumes:
      - data:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "8000:80"
    volumes:
      - data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  data: